server:
  port: 8088
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

chatgpt:
  api-key: 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    #your api-key. It can be generated in this link https://beta.openai.com/docs/quickstart/adjust-your-settings
  max-tokens: 3000
  temperature: 0.9
  topP: 1.0

